In [3]:
# Abrir xlsx usando la ruta definida
import pandas as pd
data = pd.read_excel(r"../Data/Engine_2.xlsx")
data.head()

,Component ID,Asset ID,Flota,Location,Component Profile,Lubricant,Connection Code,Observation Type,Observation Date,Observation Code,...,Plomo (ppm),Color del Refrigerante,Glycerin (%),Nitrito (ppm),PUNTO DE EBULLICION (°C),Sólidos Totales Disueltos (ppm),Turbidez (NTU),pH,Titanio (ppm),Vanadio (ppm)
0,60317 Motor,60317,R9150,CARG HID,LIEBHERR R9150 Motor,Terpel MAXTER PROGRESA 15W-40 API CI-4 PLUS,0060317 MOTR,Fluid Analysis,2025-01-26,0060317 MOTR 20250126,...,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,60149 Motor,60149,HITA3600-6,CARG HID,HITACHI EX3600-6 Motor (Cummins QSK60 Tier2),Terpel MAXTER PROGRESA 15W-40 API CI-4 PLUS,0060149 MOTR,Fluid Analysis,2025-01-26,0060149 MOTR 20250126,...,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60134 Motor,60134,HITA3600-6,CARG HID,HITACHI EX3600-6 Motor (Cummins QSK60 Tier2),Terpel MAXTER PROGRESA 15W-40 API CI-4 PLUS,0060134 MOTR,Fluid Analysis,2025-01-25,0060134 MOTR 20250125,...,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,60122 Motor - LH,60122,HITA EX5500,CARG HID,HITACHI EX5500-6 Motor (Cummins QSK50 Tier2),Terpel MAXTER PROGRESA 15W-40 API CI-4 PLUS,0060122 MOTRI,Fluid Analysis,2025-01-25,0060122 MOTRI 20250125,...,0.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60122 Motor - RH,60122,HITA EX5500,CARG HID,HITACHI EX5500-6 Motor (Cummins QSK50 Tier2),Terpel MAXTER PROGRESA 15W-40 API CI-4 PLUS,0060122 MOTRD,Fluid Analysis,2025-01-25,0060122 MOTRD 20250125,...,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Anonimizar columnas específicas manteniendo formato categórico
columns_to_anonymize = ['Component ID', 'Asset ID', 'Flota', 'Location', 'Component Profile',
                        'Lubricant', 'Connection Code', 'Observation Code', 'Reviewer']

for column in columns_to_anonymize:
    # Crear categorías únicas
    categories = data[column].astype('category')
    # Crear mapeo con prefijo basado en el nombre de la columna
    prefix = column.replace(' ', '_')
    mapping = {cat: f"{prefix}_{i+1}" for i, cat in enumerate(categories.cat.categories)}
    # Aplicar el mapeo
    data[column] = data[column].map(mapping).astype('category')

data.head()

,Component ID,Asset ID,Flota,Location,Component Profile,Lubricant,Connection Code,Observation Type,Observation Date,Observation Code,...,Plomo (ppm),Color del Refrigerante,Glycerin (%),Nitrito (ppm),PUNTO DE EBULLICION (°C),Sólidos Totales Disueltos (ppm),Turbidez (NTU),pH,Titanio (ppm),Vanadio (ppm)
0,Component_ID_54,Asset_ID_42,Flota_3,Location_1,Component_Profile_4,Lubricant_1,Connection_Code_63,Fluid Analysis,2025-01-26,Observation_Code_4112,...,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Component_ID_42,Asset_ID_30,Flota_2,Location_1,Component_Profile_1,Lubricant_1,Connection_Code_46,Fluid Analysis,2025-01-26,Observation_Code_3219,...,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Component_ID_28,Asset_ID_16,Flota_2,Location_1,Component_Profile_1,Lubricant_1,Connection_Code_32,Fluid Analysis,2025-01-25,Observation_Code_2161,...,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Component_ID_19,Asset_ID_10,Flota_1,Location_1,Component_Profile_2,Lubricant_1,Connection_Code_24,Fluid Analysis,2025-01-25,Observation_Code_1738,...,0.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Component_ID_20,Asset_ID_10,Flota_1,Location_1,Component_Profile_2,Lubricant_1,Connection_Code_23,Fluid Analysis,2025-01-25,Observation_Code_1732,...,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Renombrar algunas columnas
data = data.rename(columns={'Trakka Rating': 'Rule Based Rating'})

data.head()

,Component ID,Asset ID,Flota,Location,Component Profile,Lubricant,Connection Code,Observation Type,Observation Date,Observation Code,...,Plomo (ppm),Color del Refrigerante,Glycerin (%),Nitrito (ppm),PUNTO DE EBULLICION (°C),Sólidos Totales Disueltos (ppm),Turbidez (NTU),pH,Titanio (ppm),Vanadio (ppm)
0,Component_ID_54,Asset_ID_42,Flota_3,Location_1,Component_Profile_4,Lubricant_1,Connection_Code_63,Fluid Analysis,2025-01-26,Observation_Code_4112,...,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Component_ID_42,Asset_ID_30,Flota_2,Location_1,Component_Profile_1,Lubricant_1,Connection_Code_46,Fluid Analysis,2025-01-26,Observation_Code_3219,...,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Component_ID_28,Asset_ID_16,Flota_2,Location_1,Component_Profile_1,Lubricant_1,Connection_Code_32,Fluid Analysis,2025-01-25,Observation_Code_2161,...,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Component_ID_19,Asset_ID_10,Flota_1,Location_1,Component_Profile_2,Lubricant_1,Connection_Code_24,Fluid Analysis,2025-01-25,Observation_Code_1738,...,0.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Component_ID_20,Asset_ID_10,Flota_1,Location_1,Component_Profile_2,Lubricant_1,Connection_Code_23,Fluid Analysis,2025-01-25,Observation_Code_1732,...,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Guardar el dataframe anonimizado a un csv
data.to_csv(r"../Data/Data_Anonimizada.csv", index=False)